# Change these first
owner: vb4life # Your GitHub username
repo: test # Your GitHub repository name

# Add your sites here
sites:
  - name: Website
    url: https://www.configura.com/
  - name: MyConfigura
    url: https://my.configura.com/index.pl?page=login
  - name: Jira
    url: https://jira.configura.com/secure/Dashboard.jspa
  - name: GitLab
    url: https://git.configura.com/users/sign_in
    icon: https://about.gitlab.com/ico/favicon.ico
  - name: GitLab SSH
    url: git.configura.com
    icon: https://about.gitlab.com/ico/favicon.ico
    port: 22

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: upptime.configura.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://downloads.configura.com/web/img/logos/configura.svg
  name: Status
  # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  # introMessage: This is a test status page for Configura services

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
assignees:
  - vb4life
user-agent: vb4life
